const ERROR_TYPES = {
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DUPLICATE_KEY: 'DUPLICATE_KEY',
    CAST_ERROR: 'CAST_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
}

module.exports = ERROR_TYPES
